---
title: "Compiler Error CS0103 | Microsoft Docs"
ms.custom: ""
ms.date: "11/17/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "devlang-csharp"
ms.tgt_pltfrm: ""
ms.topic: "error-reference"
f1_keywords: 
  - "CS0103"
dev_langs: 
  - "CSharp"
helpviewer_keywords: 
  - "CS0103"
ms.assetid: fd1f2104-a945-4dba-8137-8ef869826062
caps.latest.revision: 13
caps.handback.revision: 13
author: "BillWagner"
ms.author: "wiwagn"
manager: "wpickett"
---
# Compiler Error CS0103
Der Name "Bezeichner" ist im aktuellen Kontext nicht vorhanden  
  
 Es wurde versucht, einen Namen zu verwenden, der in der Klasse, im [Namespace](../../../csharp/language-reference/keywords/namespace.md) oder im Bereich nicht vorhanden ist.  Überprüfen Sie die Schreibweise des Namens und überprüfen Sie die using\-Direktiven und die Assemblyverweise, um sicherzustellen, dass der Name, den Sie versuchen, Verwenden, verfügbar ist.  
  
 Dieser Fehler tritt häufig, wenn Sie eine Variable in einer Schleife oder in einem `try` oder `if`\-Block deklariert und dann versuchen, von einem einschließenden Codeblock oder von einem anderen Codeblock darauf zuzugreifen, wie im folgenden Beispiel gezeigt auf.  
  
```c#  
using System;  
  
class MyClass1  
{  
    public static void Main()  
    {  
        try  
        {  
            // The following declaration is only available inside the try block.  
            MyClass1 conn = new MyClass1();  
        }  
        catch (Exception e)  
        {  
            // The following expression causes error CS0103, because variable  
            // conn only exists in the try block.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
  
```  
  
 Im folgenden Beispiel löst den Fehler auf.  
  
```c#  
  
using System;  
  
class MyClass2  
{  
    public static void Main()  
    {  
        // To resolve the error in the example, the first step is to   
        // move the declaration of conn out of the try block. The following  
        // declaration is available throughout the Main method.  
        MyClass2 conn = null;  
        try  
        {  
            // Inside the try block, use the conn variable that you declared  
            // previously.  
            conn = new MyClass2();  
        }  
        catch (Exception e)  
        {  
            // The following expression no longer causes an error, because  
            // the declaration of conn is in scope.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
  
```